# Generated by Django 3.2.9 on 2021-11-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('scheduled_for', models.DateField()),
                ('is_same_day', models.BooleanField()),
            ],
        ),
    ]
